server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always
      platform: h2
    job:
        enabled: false
  application:
    name: STUDENT-SERVICE
    config:
      import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
temp:
  storage:
    directory: /home/vasu/Documents/
